services:
  web:
    image: lovasoa/sqlpage:main
    ports:
      - "8080:8080"
    environment:
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_TLS_MODE: none
      SMTP_FROM: SQLPage Demo <sqlpage@example.com>
    volumes:
      - .:/var/www
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit:v1.30.4
    ports:
      - "8025:8025"
