select 'dynamic' as component,'{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"dynamic","properties":
{"component":"text", "contents": "It works ! (but it shouldn''t)"}
}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
' as properties;