-- Generated by scripts/generate_configuration_reference.py from sqlpage/sqlpage.schema.json.
-- Do not edit this file directly.
select 'dynamic' as component, json_patch(json_extract(properties, '$[0]'), json_object(
    'title', 'SQLPage configuration reference'
)) as properties from example where component = 'shell' limit 1;

select 'text' as component;
select '# SQLPage configuration reference

SQLPage reads `sqlpage/sqlpage.json`. Add the [`$schema`](https://json-schema.org/understanding-json-schema/reference/schema) property to get validation and editor completion. Every option can also be supplied as an uppercase environment variable; environment variables override file values.

The [JSON Schema](https://github.com/sqlpage/SQLPage/raw/refs/heads/main/sqlpage/sqlpage.schema.json) is the source of truth for this reference and SQLPage''s in-memory configuration structure.' as contents_md;

select 'table' as component, true as sort, true as search;
select 'database_url' as option, 'string' as type, '—' as default_value, 'Database connection URL or ODBC connection string.' as description union all
select 'database_password' as option, 'string' as type, '—' as default_value, 'Database password. When set, overrides a password embedded in database_url.' as description union all
select 'max_database_pool_connections' as option, 'integer' as type, '—' as default_value, 'Maximum number of simultaneous database connections.' as description union all
select 'database_connection_idle_timeout_seconds' as option, 'number' as type, '—' as default_value, 'Close idle database connections after this many seconds. Use 0 to disable.' as description union all
select 'database_connection_max_lifetime_seconds' as option, 'number' as type, '—' as default_value, 'Close database connections after this many seconds regardless of activity. Use 0 to disable.' as description union all
select 'sqlite_extensions' as option, 'array' as type, '[]' as default_value, 'SQLite extensions to load when connecting.' as description union all
select 'listen_on' as option, 'string' as type, '—' as default_value, 'Socket address on which the HTTP server listens. Defaults to 0.0.0.0:8080, or port 443 with https_domain.' as description union all
select 'port' as option, 'integer or string' as type, '—' as default_value, 'TCP port on which to listen. A Kubernetes service URI is ignored for compatibility.' as description union all
select 'unix_socket' as option, 'string' as type, '—' as default_value, 'UNIX socket path to listen on instead of TCP.' as description union all
select 'database_connection_retries' as option, 'integer' as type, '6' as default_value, 'Number of database connection retries at startup, five seconds apart.' as description union all
select 'database_connection_acquire_timeout_seconds' as option, 'number' as type, '10' as default_value, 'Maximum seconds to wait for a connection from the database pool.' as description union all
select 'web_root' as option, 'string' as type, '"."' as default_value, 'Directory containing the SQL files served by SQLPage.' as description union all
select 'configuration_directory' as option, 'string' as type, '"./sqlpage"' as default_value, 'Directory containing SQLPage configuration, templates, and migrations.' as description union all
select 'allow_exec' as option, 'boolean' as type, 'false' as default_value, 'Allow SQL queries to call sqlpage.exec. Enable only when all SQL authors are trusted.' as description union all
select 'max_uploaded_file_size' as option, 'integer' as type, '5242880' as default_value, 'Maximum uploaded file size in bytes.' as description union all
select 'oidc_issuer_url' as option, 'string' as type, '—' as default_value, 'Base URL of the OpenID Connect provider.' as description union all
select 'oidc_client_id' as option, 'string' as type, '"sqlpage"' as default_value, 'OIDC client ID assigned to SQLPage.' as description union all
select 'oidc_client_secret' as option, 'string' as type, '—' as default_value, 'OIDC client secret assigned to SQLPage.' as description union all
select 'oidc_scopes' as option, 'string' as type, '"openid email profile"' as default_value, 'Space-separated OIDC scopes requested during authentication.' as description union all
select 'oidc_protected_paths' as option, 'array' as type, '["/"]' as default_value, 'Path prefixes that require OIDC authentication. Public paths take precedence.' as description union all
select 'oidc_public_paths' as option, 'array' as type, '[]' as default_value, 'Path prefixes excluded from OIDC authentication.' as description union all
select 'oidc_additional_trusted_audiences' as option, 'array' as type, '—' as default_value, 'Additional trusted OIDC JWT audiences. Null trusts all additional audiences; an empty array trusts only the client ID.' as description union all
select 'https_domain' as option, 'string' as type, '—' as default_value, 'Domain name for automatic HTTPS with a Let’s Encrypt certificate.' as description union all
select 'host' as option, 'string' as type, '—' as default_value, 'Public hostname used for OIDC redirect URLs. Defaults to https_domain.' as description union all
select 'https_certificate_email' as option, 'string' as type, '—' as default_value, 'Email address used when requesting the automatic HTTPS certificate.' as description union all
select 'https_certificate_cache_dir' as option, 'string' as type, '"./sqlpage/https"' as default_value, 'Directory used to store automatic HTTPS certificates.' as description union all
select 'https_acme_directory_url' as option, 'string' as type, '"https://acme-v02.api.letsencrypt.org/directory"' as default_value, 'ACME directory URL used for automatic HTTPS certificates.' as description union all
select 'environment' as option, 'string' as type, '"development"' as default_value, 'Runtime environment, controlling whether detailed errors are shown.' as description union all
select 'site_prefix' as option, 'string' as type, '"/"' as default_value, 'URL path prefix from which the site is served. SQLPage normalizes leading and trailing slashes.' as description union all
select 'max_pending_rows' as option, 'integer' as type, '256' as default_value, 'Maximum number of result rows buffered before sending them to the client.' as description union all
select 'compress_responses' as option, 'boolean' as type, 'false' as default_value, 'Compress HTTP response bodies when supported by the client.' as description union all
select 'content_security_policy' as option, 'string' as type, '—' as default_value, 'Content-Security-Policy header template. Use {{@csp_nonce}} for SQLPage’s generated nonce.' as description union all
select 'system_root_ca_certificates' as option, 'boolean' as type, 'false' as default_value, 'Load trusted certificates from the operating system certificate store for sqlpage.fetch.' as description union all
select 'max_recursion_depth' as option, 'integer' as type, '10' as default_value, 'Maximum recursion depth for run_sql.' as description union all
select 'markdown_allow_dangerous_html' as option, 'boolean' as type, 'false' as default_value, 'Allow raw HTML in Markdown.' as description union all
select 'markdown_allow_dangerous_protocol' as option, 'boolean' as type, 'false' as default_value, 'Allow dangerous URL protocols in Markdown links.' as description union all
select 'cache_stale_duration_ms' as option, 'integer' as type, '—' as default_value, 'Milliseconds for which cached SQL files remain fresh. Defaults to 0 in development and 1000 in production.' as description;
