//! Built-in `SQLPage` SQL functions.
//!
//! Every function is a plain `async fn` in its own module under [`functions/`](self). To add one,
//! just create `functions/<name>.rs` with an `async fn <name>`: `build.rs` discovers it and emits
//! a [`sqlpage_functions!`](super::function_traits::sqlpage_functions) call (the file `include!`d
//! below) that declares the module and adds it to the dispatch enum. Argument conversion and
//! dispatch are handled generically in [`super::function_traits`].

// Every function module reaches the shared imports below, and its siblings' `pub(super)` helpers,
// through `use super::*`. Allow it once here rather than on each module.
#![allow(clippy::wildcard_imports)]

use super::{ExecutionContext, RequestInfo};
use crate::filesystem::FileAccess;
use crate::webserver::{
    ErrorWithStatus,
    database::{
        blob_to_data_url::vec_to_data_uri_with_mime,
        execute_queries::DbConn,
        sqlpage_functions::{http_fetch_request::HttpFetchRequest, url_parameters::URLParameters},
    },
    http_client::make_http_client,
    request_variables::SetVariablesMap,
    single_or_vec::SingleOrVec,
};
use anyhow::{Context, anyhow};
use futures_util::StreamExt;
use mime_guess::mime;
use opentelemetry_semantic_conventions::attribute as otel;
use std::fmt::Write;
use std::{borrow::Cow, ffi::OsStr, str::FromStr};
use tracing::Instrument;

use super::function_traits::sqlpage_functions;

// Generated by build.rs: a `sqlpage_functions!` call listing every module file in `functions/`.
// Discovering them there is what frees us from a hand-maintained registry.
include!(concat!(env!("OUT_DIR"), "/sqlpage_functions.rs"));
