load_module modules/ngx_otel_module.so;

events {}

http {
    otel_exporter {
        endpoint otel-collector:4317;
    }

    otel_service_name nginx;
    otel_trace on;
    otel_trace_context propagate;

    upstream sqlpage {
        server sqlpage:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://sqlpage;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
