services:
  web:
    image: lovasoa/sqlpage:main
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
      - ./sqlpage:/etc/sqlpage
    environment:
      DATABASE_URL: sqlite:///tmp/components.db?mode=rwc
